title: MLOps Digest
description: A newsletter for MLOps, ML engineering, and AI infra.
theme: minima  # official Jekyll theme; you can pick others!
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  math_engine: mathjax
